// src/components/sidebar/friendly-links.tsx
import React from 'react'
import { Separator } from 'blackwork'
import { Link } from '@/navigation'
import { SidebarBlock } from '../shared/sidebar-block'
import { type linkItem } from '@/types'

const links: readonly linkItem[] = [
  {
    href: 'https://vue3.chengpeiquan.com',
    title: 'Vue3 入门指南与实战案例',
  },
  {
    href: 'https://www.fnnas.com',
    title: '飞牛 NAS',
  },
  {
    href: 'https://chawyehsu.com',
    title: 'The Art of Chawye Hsu',
  },
  {
    href: 'https://guangne.com',
    title: '旅行家龙猫',
  },
  {
    href: 'https://muki.tw',
    title: 'Muki Space',
  },
]

export const FriendlyLinks: React.FC = () => {
  return (
    <SidebarBlock title="友情链接">
      <div className="w-full space-x-3 space-y-2">
        {links.map((i, idx) => {
          return (
            <>
              {idx > 0 && (
                <Separator
                  orientation="vertical"
                  className="inline-block align-middle h-4 !my-0"
                />
              )}

              <Link
                key={i.href}
                href={i.href}
                target="_blank"
                rel="nofollow noopener noreferrer"
                className="text-sm"
              >
                {i.title}
              </Link>
            </>
          )
        })}
      </div>
    </SidebarBlock>
  )
}

// src/components/FriendlyLinks.vue
<template>
  <section class="mb-2">
    <h2 class="block-title">友情链接</h2>
    <div class="flex flex-wrap w-full text-base">
      <a
        class="mb-2"
        href="https://vue3.chengpeiquan.com/"
        target="_blank"
        rel="noopener noreferrer"
        >Vue3入门指南与实战案例</a
      >
      <span class="text-gray-900 mx-2">|</span>
      <a
        class="mb-2"
        href="https://chawyehsu.com/"
        target="_blank"
        rel="noopener noreferrer"
        >The Art of Chawye Hsu</a
      >
      <span class="text-gray-900 mx-2">|</span>
      <a
        class="mb-2"
        href="https://guangne.com/"
        target="_blank"
        rel="noopener noreferrer"
        >旅行家龙猫</a
      >
      <span class="text-gray-900 mx-2">|</span>
      <a
        class="mb-2"
        href="https://muki.tw/"
        target="_blank"
        rel="noopener noreferrer"
        >Muki Space</a
      >
    </div>
  </section>
</template>

<style lang="postcss" scoped>
.block-title {
  @apply text-xl font-bold mb-4 pb-4 border-b dark:border-white dark:border-opacity-5;
}
</style>
